// Generates QR and Barcode image URLs for a tracking code
// Uses public CDN-based APIs — no extra npm packages needed

const TRACKING_BASE_URL = process.env.PUBLIC_TRACKING_URL || process.env.FRONTEND_URL || 'https://kdmexpress.com';

/**
 * Returns the full tracking URL that the QR code will point to.
 * When scanning the QR with a phone, the browser will open this URL directly.
 */
export const getTrackingUrl = (trackingCode) => {
  const base = (TRACKING_BASE_URL && !TRACKING_BASE_URL.includes('localhost') && !TRACKING_BASE_URL.includes('127.0.0.1'))
    ? TRACKING_BASE_URL
    : 'https://kdmexpress.com';
  return `${base}/track?code=${trackingCode}`;
};

/**
 * Returns a URL to a QR code image generated by qrserver.com.
 * The QR encodes the full tracking page URL for one-click mobile scanning.
 */
export const generateQrCodeUrl = (trackingCode) => {
  const trackingUrl = encodeURIComponent(getTrackingUrl(trackingCode));
  return `https://api.qrserver.com/v1/create-qr-code/?size=200x200&ecc=M&data=${trackingUrl}`;
};

/**
 * Returns a URL to a Code-128 barcode image generated by barcodeapi.org.
 * The barcode encodes just the raw tracking code for fast scanner gun reads.
 */
export const generateBarcodeUrl = (trackingCode) =>
  `https://barcodeapi.org/api/128/${trackingCode}`;

/**
 * Returns both URLs together for convenience.
 */
export const generateLabelUrls = (trackingCode) => ({
  qrCodeUrl: generateQrCodeUrl(trackingCode),
  barcodeUrl: generateBarcodeUrl(trackingCode),
});
