services:
  mongodb:
    image: mongo:6.0
    container_name: ktmexpress_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: ktmexpress_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=
      - JWT_SECRET=
      - CLIENT_URL=
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    container_name: ktmexpress_frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
